### ISSUE TITLE
Raise, or completely remove "assets" limit for core users that selfhost.

### ISSUE THREAD

**Issue by PhoenixSheppy** [bgenev/impulse-xdr#1]
The whole point of selfhosting is to have the freedom to do whatever you want with the software you host.

By imposing restrictions like license limitations and soft-limits, you defeat the purpose of selfhosting in the first place.

I personally use Wazuh right now, but I really like the design of your app, I'd ideally like to use it with 15-20 hosts on my network, but I don't want to sinkhole on a subscription plan for something that runs mostly* onsite.

This feels more like a _freemium experience_. Nothing personal, just calling it how I see it.

Thanks,
JW.

**Comment by PhoenixSheppy** [comment]
*In an effort to be more constructive, I'd like to build off your comment you posted on reddit;
![image](https://github.com/bgenev/impulse-xdr/assets/20131900/468265f4-e36d-467a-869a-ff99cc229f79)

This is something I'd be onboard with, features that require things like APIs and external costs, that makes sense, and I totally get that, but try not to go overboard on this in particular. A fine balance of "this costs money to operate" and "this is purely a software feature" is something I'd like to see personally.

**Comment by bgenev** [comment]
Thanks, appreciate the input! Next version will include more assets in the free-tier as part of a "home-lab" plan for testing. Stay tuned!

Wazuh was mentioned a couple of times, however this is a completely different product with a different approach to intrusion detection that provides greater visibility and catches events that go unnoticed by Wazuh. If you want to play with it, try running the advanced persistent threat scripts from here https://flaviu.io/advanced-persistent-threat/ on a VM running Wazuh and Impulse agents head-to-head, and you'll see the difference.

**Comment by bgenev** [comment]
Free-tier is now 10
