### ISSUE TITLE
setup error when Password has a @ symbol in IMPULSE_DB_SERVER_PWD

### ISSUE THREAD

**Issue by buyenne** [bgenev/impulse-xdr#3]
Ubuntu 22.04 in a LXD container on Proxmox. 
Forgot to copy the exact log but it was showing somethign like _could not translate host name 22@127.0.0.1 to address_
PW Block ended with @22. 
Easy fix was:
- ./uninstall_manager.sh
- ./install_manager.sh
Cheers.

**Comment by bgenev** [comment]
Thanks, will investigate this setup later. The password issue will be fixed in the next release. 

For now, you should install on VM with password that doesn't contain special characters.
