### ISSUE TITLE
Minor UI issue

### ISSUE THREAD

**Issue by bennos1911** [bgenev/impulse-xdr#4]
In the Instance Overview - Asset Posture page  (#/fleet/asset/details/asset-*) - column heading reads 'Satus' should be 'Status'

![Screenshot 2024-03-25 150718](https://github.com/bgenev/impulse-xdr/assets/153687785/dc8d1b67-853c-4c2c-9f39-965a950d48de)

Impulse-XDR Version - v.1.9
Manager OS - Ubuntu 22.04 Proxmox LXC CT

**Comment by bgenev** [comment]
Thanks
